site_name: Central Expresso
site_author: Grupo 8
site_description: >-
  Documentação para o projeto realizado na disciplina de Interação Humano Computador da Universidade de Brasília.

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Início: index.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Processo de Design: planejamento/processo_design.md
      - Sites Avaliados: planejamento/sites_avaliados.md
      - Site Escolhido: planejamento/site_escolhido.md
  - Atas:
      - Ata 1: atas/ata1.md
      - Ata 2: atas/ata2.md
      - Ata 3: atas/ata3.md
      - Ata 4: atas/ata4.md
      - Ata 5: atas/ata5.md
      - Ata 6: atas/ata6.md
      - Ata 7: atas/ata7.md
      - Ata 8: atas/ata8.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao_1.md
      - Apresentação 2: apresentacoes/apresentacao_2.md
      - Apresentação 3: apresentacoes/apresentacao_3.md
  - Análise de Requisitos:
      - Aspectos Éticos: requisitos/etica.md
      - Perfil de Usuários: requisitos/perfil_usuarios.md
      - Personas: requisitos/personas.md
      - Cenários: requisitos/cenarios.md
      - Análise de Tarefas:
          - HTA: requisitos/analise_tarefas_hta.md
          - GOMS: requisitos/analise_tarefas_goms.md
      - Características da Plataforma: requisitos/caracteristicas_gerais.md
      - Princípios Gerais do Projeto: requisitos/principios_gerais.md
      - Metas de Usabilidade: requisitos/metas_usabilidade.md
      - Guia de Estilo: requisitos/guia_estilo.md
  - Design, Avaliação e Desenvolvimento:
      - Planejamento do Relato dos Resultados da Avaliação : Design_avaliacao/PlanejamentoResultadosA.md
extra_css:
  - custom.css
