site_name: Central Expresso
site_author: Grupo 8
site_description: >-
  Documentação para o projeto realizado na disciplina de Interação Humano Computador da Universidade de Brasília.

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Início: index.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Processo de Design: planejamento/processo_design.md
      - Sites Avaliados: planejamento/sites_avaliados.md
      - Site Escolhido: planejamento/site_escolhido.md
  - Atas:
      - Ata 1: atas/ata1.md
      - Ata 2: atas/ata2.md
      - Ata 3: atas/ata3.md
      - Ata 4: atas/ata4.md
      - Ata 5: atas/ata5.md
      - Ata 6: atas/ata6.md
      - Ata 7: atas/ata7.md
      - Ata 8: atas/ata8.md
      - Ata 9: atas/ata9.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao_1.md
      - Apresentação 2: apresentacoes/apresentacao_2.md
      - Apresentação 3: apresentacoes/apresentacao_3.md
      - Apresentação 4: apresentacoes/apresentacao_4.md
      - Apresentação 5: apresentacoes/apresentacao_5.md
      - Apresentação 6.1: apresentacoes/apresentacao_6_1.md
      - Apresentação 6.2: apresentacoes/apresentacao_6_2.md
      - Apresentação 7: apresentacoes/apresentacao_7.md
      - Apresentação 8: apresentacoes/apresentacao_8.md
      - Apresentação Final: apresentacoes/apresentacao_final.md
  - Análise de Requisitos:
      - Aspectos Éticos: requisitos/etica.md
      - Perfil de Usuários: requisitos/perfil_usuarios.md
      - Personas: requisitos/personas.md
      - Cenários: requisitos/cenarios.md
      - Análise de Tarefas:
          - HTA: requisitos/analise_tarefas_hta.md
          - GOMS: requisitos/analise_tarefas_goms.md
      - Características da Plataforma: requisitos/caracteristicas_gerais.md
      - Princípios Gerais do Projeto: requisitos/principios_gerais.md
      - Metas de Usabilidade: requisitos/metas_usabilidade.md
      - Guia de Estilo: requisitos/guia_estilo.md
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
          - StoryBoard:
              - Storyboard: design_avaliacao/nivel_1/storyboard/storyboard.md
              - Planejamento da Avaliação do Storyboard: design_avaliacao/nivel_1/storyboard/planejamento_avaliacao.md
              - Planejamento do Relato dos Resultados da Avaliação do Storyboard: design_avaliacao/nivel_1/storyboard/planejamento_resultados.md
              - Relato dos Resultados da Avaliação do Storyboard: design_avaliacao/nivel_1/storyboard/relato_resultados.md
          - Análise de Tarefas:
              - Planejamento da Avaliação da Análise de Tarefas: design_avaliacao/nivel_1/analise_tarefas/planejamento_avaliacao.md
              - Planejamento do Relato da Avaliação da Análise de Tarefas: design_avaliacao/nivel_1/analise_tarefas/planejamento_relato_avaliacao.md
              - Relato da Avaliação da Análise de Tarefas: design_avaliacao/nivel_1/analise_tarefas/relato_avaliacao.md
      - Nível 2:
          - Protótipo de Papel:
              - Planejamento da Avaliação do Protótipo de Papel: design_avaliacao/nivel_2/prototipo_papel/planejamento_avaliacao.md
              - Planejamento do Relato dos Resultados da Avaliação do Protótipo de Papel: design_avaliacao/nivel_2/prototipo_papel/planejamento_relato.md
              - Protótipo de Papel: design_avaliacao/nivel_2/prototipo_papel/prototipo_papel.md
              - Relato dos Resultados da Avaliação do Protótipo de Papel: design_avaliacao/nivel_2/prototipo_papel/relato.md
      - Nível 3:
          - Protótipo de Alta Fidelidade:
              - Planejamento da Avaliação do Protótipo de Alta Fidelidade: Design_avaliacao/nivel_3/planejamento_avaliacao_PAF.md
              - Planejamento do Relato da Avaliação do Protótipo de Alta Fidelidade: Design_avaliacao/nivel_3/planejamento_relato_PAF.md
              - Protótipo de Alta Fidelidade: Design_avaliacao/nivel_3/prototipo_AF.md
              - Relato dos Resultados da Avaliação do Protótipo de Alta Fidelidade: Design_avaliacao/nivel_3/relato.md
  - Verificação:
      - Grupo 1 (CD-MOJ):
        - Planejamento da Verificação: verificacao/planej_verificacao.md
        - Análise de Requisitos:
          - Planejamento da Verificação dos Artefatos: verificacao/requisitos/planej_verificacao.md
          - Verificação: verificacao/requisitos/verificacao.md
        - Design, Avaliação e Desenvolvimento:
          - Planejamento da Verificação dos Artefatos: verificacao/design_avaliacao/planej_verificacao.md
          - Verificação: verificacao/design_avaliacao/verificacao.md
      - Grupo 8 (Central Expresso):
        - Planejamento da Verificação: verificacao_grupo/planej_verificacao.md
        - Análise de Requisitos:
          - Planejamento da Verificação dos Artefatos: verificacao_grupo/requisitos/planej_verificacao.md
          - Verificação: verificacao_grupo/requisitos/verificacao.md
        - Design, Avaliação e Desenvolvimento:
          - Planejamento da Verificação dos Artefatos: verificacao_grupo/design_avaliacao/planej_verificacao.md
          - Verificação: verificacao_grupo/design_avaliacao/verificacao.md
  - Entrega Final:
      - Site Selecionado: entrega_final/site_selecionado.md
      - Ciclo de Vida Utilizado: entrega_final/ciclo_vida.md
      - Planejamento dos Recursos e das Entregas (cronogramas): entrega_final/cronogramas.md
      - Execução do Projeto: entrega_final/execucao.md
      - Resultados Alcançados com a Execução do Projeto: entrega_final/resultados_alcançados.md
      - Ferramentas: entrega_final/ferramentas.md
      - Técnicas Utilizadas: entrega_final/tecnicas_utilizadas.md
      - Artefatos Criados: entrega_final/artefatos.md
      - Avaliações dos Protótipos: entrega_final/avaliacoes_prototipos.md
      - Verificações: entrega_final/verificacoes.md
      - Apresentações: entrega_final/apresentacoes.md
      - Considerações Finais: entrega_final/consideracoes_finais.md


extra_css:                                        
  - custom.css
